# Generated by Django 4.0.4 on 2022-05-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_rename_auteur_csgo_lieu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csgo',
            old_name='dates',
            new_name='date_debut',
        ),
        migrations.AddField(
            model_name='csgo',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
