# Generated by Django 4.0.4 on 2022-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0003_rename_dates_csgo_date_debut_csgo_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='csgo',
            name='prix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
