# Generated by Django 4.0.4 on 2022-05-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_csgo_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='Equipe',
            new_name='Maps_Jouées',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='Stats',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='Horaire',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='major',
            name='Score',
        ),
    ]
